# -*- coding: utf-8 -*-
"""PSO_DCmotorPID.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IvLm-0ocIouUDr6kHo2Vz0WFJC1Mx5qt
"""

import numpy as np
import matplotlib.pyplot as plt

J, b, K, R, L = 0.01, 0.1, 0.01, 1.0, 0.5
A = np.array([[-b/J, K/J], [-K/L, -R/L]])
B = np.array([[0], [1/L]])
C = np.array([1, 0])

def dc_motor_step(x, V, dt=0.01):
    return x + (A @ x + B * V) * dt, C @ x

def simulate_pid_motor(pid_gains, duration=5.0, dt=0.01, setpoint=1.0):
    Kp, Ki, Kd = pid_gains
    num_steps = int(duration / dt)
    t_eval = np.linspace(0, duration, num_steps)
    x = np.zeros((2, 1))
    integral_error = 0.0
    prev_error = 0.0
    y_history, u_history = [], []
    itae = 0.0

    for t in t_eval:
        y = x[0, 0]
        y_history.append(y)
        error = setpoint - y
        integral_error += error * dt
        derivative_error = (error - prev_error) / dt
        u = np.clip(Kp * error + Ki * integral_error + Kd * derivative_error, -24.0, 24.0)
        u_history.append(u)
        x, _ = dc_motor_step(x, u, dt)
        itae += t * abs(error) * dt
        prev_error = error

    return itae, t_eval, y_history, u_history

def pid_objective(gains):
    if np.any(gains < 0):
        return 1e6
    cost, _, _, _ = simulate_pid_motor(gains, duration=3.0)
    return cost

best_gains, best_cost = particle_swarm_optimization(
    pid_objective, N=30, T=50, w=0.6, c1=1.5, c2=1.5,
    lower_bound=[0.1, 0.0, 0.0], upper_bound=[50.0, 50.0, 10.0]
)

print(f"Optimized Gains [Kp, Ki, Kd]: {best_gains}")
print(f"Minimum ITAE Cost: {best_cost:.4f}")

cost, t_eval, y, u = simulate_pid_motor(best_gains, duration=4.0)
plt.figure(figsize=(12, 4))
plt.subplot(1, 2, 1)
plt.plot(t_eval, y, label='Speed', color='blue')
plt.axhline(1.0, color='red', linestyle='--')
plt.grid(True)
plt.legend()
plt.subplot(1, 2, 2)
plt.plot(t_eval, u, label='Voltage', color='orange')
plt.grid(True)
plt.legend()
plt.show()